//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRfidTekni
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRfidTekni.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsumirApi", ReplyAction="http://tempuri.org/IService1/ConsumirApiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.ConsumirApiResponse> ConsumirApiAsync(ServiceRfidTekni.ConsumirApiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reseptor", ReplyAction="http://tempuri.org/IService1/ReseptorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.ReseptorResponse> ReseptorAsync(ServiceRfidTekni.ReseptorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProWhcol133", ReplyAction="http://tempuri.org/IService1/ProWhcol133Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.ProWhcol133Response> ProWhcol133Async(ServiceRfidTekni.ProWhcol133Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProWhcol133Ora", ReplyAction="http://tempuri.org/IService1/ProWhcol133OraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.ProWhcol133OraResponse> ProWhcol133OraAsync(ServiceRfidTekni.ProWhcol133OraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update133ss", ReplyAction="http://tempuri.org/IService1/Update133ssResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.Update133ssResponse> Update133ssAsync(ServiceRfidTekni.Update133ssRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectWhcol133Oss", ReplyAction="http://tempuri.org/IService1/SelectWhcol133OssResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133OssResponse> SelectWhcol133OssAsync(ServiceRfidTekni.SelectWhcol133OssRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectWhcol133ORfidss", ReplyAction="http://tempuri.org/IService1/SelectWhcol133ORfidssResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133ORfidssResponse> SelectWhcol133ORfidssAsync(ServiceRfidTekni.SelectWhcol133ORfidssRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectWhcol131Ora", ReplyAction="http://tempuri.org/IService1/SelectWhcol131OraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol131OraResponse> SelectWhcol131OraAsync(ServiceRfidTekni.SelectWhcol131OraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectTicol011McnoOra", ReplyAction="http://tempuri.org/IService1/SelectTicol011McnoOraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectTicol011McnoOraResponse> SelectTicol011McnoOraAsync(ServiceRfidTekni.SelectTicol011McnoOraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertTicol080Ora", ReplyAction="http://tempuri.org/IService1/InsertTicol080OraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.InsertTicol080OraResponse> InsertTicol080OraAsync(ServiceRfidTekni.InsertTicol080OraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectWhcol133Evnt", ReplyAction="http://tempuri.org/IService1/SelectWhcol133EvntResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133EvntResponse> SelectWhcol133EvntAsync(ServiceRfidTekni.SelectWhcol133EvntRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateWhcol131", ReplyAction="http://tempuri.org/IService1/UpdateWhcol131Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.UpdateWhcol131Response> UpdateWhcol131Async(ServiceRfidTekni.UpdateWhcol131Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitProcRfid", ReplyAction="http://tempuri.org/IService1/InitProcRfidResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfidResponse> InitProcRfidAsync(ServiceRfidTekni.InitProcRfidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitProcRfid022", ReplyAction="http://tempuri.org/IService1/InitProcRfid022Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfid022Response> InitProcRfid022Async(ServiceRfidTekni.InitProcRfid022Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitProcRfid025", ReplyAction="http://tempuri.org/IService1/InitProcRfid025Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfid025Response> InitProcRfid025Async(ServiceRfidTekni.InitProcRfid025Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitProcRfid025ReprintLabel", ReplyAction="http://tempuri.org/IService1/InitProcRfid025ReprintLabelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfid025ReprintLabelResponse> InitProcRfid025ReprintLabelAsync(ServiceRfidTekni.InitProcRfid025ReprintLabelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updtwhcol133RfidSS", ReplyAction="http://tempuri.org/IService1/Updtwhcol133RfidSSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.Updtwhcol133RfidSSResponse> Updtwhcol133RfidSSAsync(ServiceRfidTekni.Updtwhcol133RfidSSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectWhcol133OPaidAssing", ReplyAction="http://tempuri.org/IService1/SelectWhcol133OPaidAssingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133OPaidAssingResponse> SelectWhcol133OPaidAssingAsync(ServiceRfidTekni.SelectWhcol133OPaidAssingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert133ss", ReplyAction="http://tempuri.org/IService1/Insert133ssResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceRfidTekni.Insert133ssResponse> Insert133ssAsync(ServiceRfidTekni.Insert133ssRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsumirApi", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsumirApiRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string requestBody;
        
        public ConsumirApiRequest()
        {
        }
        
        public ConsumirApiRequest(string requestBody)
        {
            this.requestBody = requestBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsumirApiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsumirApiResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConsumirApiResult;
        
        public ConsumirApiResponse()
        {
        }
        
        public ConsumirApiResponse(string ConsumirApiResult)
        {
            this.ConsumirApiResult = ConsumirApiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Reseptor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReseptorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Rfid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Evnt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Logn;
        
        public ReseptorRequest()
        {
        }
        
        public ReseptorRequest(string Rfid, string Evnt, string Logn)
        {
            this.Rfid = Rfid;
            this.Evnt = Evnt;
            this.Logn = Logn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReseptorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReseptorResponse
    {
        
        public ReseptorResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProWhcol133", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProWhcol133Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PAID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORNO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DATE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LOGN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PROC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REFCNTD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REFCNTU;
        
        public ProWhcol133Request()
        {
        }
        
        public ProWhcol133Request(string PAID, string RFID, string EVNT, string ORNO, string DATE, string LOGN, string PROC, string REFCNTD, string REFCNTU)
        {
            this.PAID = PAID;
            this.RFID = RFID;
            this.EVNT = EVNT;
            this.ORNO = ORNO;
            this.DATE = DATE;
            this.LOGN = LOGN;
            this.PROC = PROC;
            this.REFCNTD = REFCNTD;
            this.REFCNTU = REFCNTU;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProWhcol133Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProWhcol133Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProWhcol133Result;
        
        public ProWhcol133Response()
        {
        }
        
        public ProWhcol133Response(string ProWhcol133Result)
        {
            this.ProWhcol133Result = ProWhcol133Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProWhcol133Ora", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProWhcol133OraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PAID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORNO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LOGN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PROC;
        
        public ProWhcol133OraRequest()
        {
        }
        
        public ProWhcol133OraRequest(string PAID, string RFID, string EVNT, string ORNO, string LOGN, string PROC)
        {
            this.PAID = PAID;
            this.RFID = RFID;
            this.EVNT = EVNT;
            this.ORNO = ORNO;
            this.LOGN = LOGN;
            this.PROC = PROC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProWhcol133OraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProWhcol133OraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ProWhcol133OraResult;
        
        public ProWhcol133OraResponse()
        {
        }
        
        public ProWhcol133OraResponse(bool ProWhcol133OraResult)
        {
            this.ProWhcol133OraResult = ProWhcol133OraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update133ss", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update133ssRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PAID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORNO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DATE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LOGN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PROC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REFCNTD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REFCNTU;
        
        public Update133ssRequest()
        {
        }
        
        public Update133ssRequest(string PAID, string RFID, string EVNT, string ORNO, string DATE, string LOGN, string PROC, string REFCNTD, string REFCNTU)
        {
            this.PAID = PAID;
            this.RFID = RFID;
            this.EVNT = EVNT;
            this.ORNO = ORNO;
            this.DATE = DATE;
            this.LOGN = LOGN;
            this.PROC = PROC;
            this.REFCNTD = REFCNTD;
            this.REFCNTU = REFCNTU;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update133ssResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update133ssResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Update133ssResult;
        
        public Update133ssResponse()
        {
        }
        
        public Update133ssResponse(bool Update133ssResult)
        {
            this.Update133ssResult = Update133ssResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SelectWhcol133OssResponseSelectWhcol133OssResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectWhcol133Oss", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectWhcol133OssRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVNT;
        
        public SelectWhcol133OssRequest()
        {
        }
        
        public SelectWhcol133OssRequest(string RFID, string EVNT)
        {
            this.RFID = RFID;
            this.EVNT = EVNT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectWhcol133OssResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectWhcol133OssResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceRfidTekni.SelectWhcol133OssResponseSelectWhcol133OssResult SelectWhcol133OssResult;
        
        public SelectWhcol133OssResponse()
        {
        }
        
        public SelectWhcol133OssResponse(ServiceRfidTekni.SelectWhcol133OssResponseSelectWhcol133OssResult SelectWhcol133OssResult)
        {
            this.SelectWhcol133OssResult = SelectWhcol133OssResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SelectWhcol133ORfidssResponseSelectWhcol133ORfidssResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectWhcol133ORfidss", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectWhcol133ORfidssRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVNT;
        
        public SelectWhcol133ORfidssRequest()
        {
        }
        
        public SelectWhcol133ORfidssRequest(string RFID, string EVNT)
        {
            this.RFID = RFID;
            this.EVNT = EVNT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectWhcol133ORfidssResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectWhcol133ORfidssResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceRfidTekni.SelectWhcol133ORfidssResponseSelectWhcol133ORfidssResult SelectWhcol133ORfidssResult;
        
        public SelectWhcol133ORfidssResponse()
        {
        }
        
        public SelectWhcol133ORfidssResponse(ServiceRfidTekni.SelectWhcol133ORfidssResponseSelectWhcol133ORfidssResult SelectWhcol133ORfidssResult)
        {
            this.SelectWhcol133ORfidssResult = SelectWhcol133ORfidssResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SelectWhcol131OraResponseSelectWhcol131OraResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectWhcol131Ora", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectWhcol131OraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PAID;
        
        public SelectWhcol131OraRequest()
        {
        }
        
        public SelectWhcol131OraRequest(string PAID)
        {
            this.PAID = PAID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectWhcol131OraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectWhcol131OraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceRfidTekni.SelectWhcol131OraResponseSelectWhcol131OraResult SelectWhcol131OraResult;
        
        public SelectWhcol131OraResponse()
        {
        }
        
        public SelectWhcol131OraResponse(ServiceRfidTekni.SelectWhcol131OraResponseSelectWhcol131OraResult SelectWhcol131OraResult)
        {
            this.SelectWhcol131OraResult = SelectWhcol131OraResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SelectTicol011McnoOraResponseSelectTicol011McnoOraResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectTicol011McnoOra", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectTicol011McnoOraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MCNO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string STAT;
        
        public SelectTicol011McnoOraRequest()
        {
        }
        
        public SelectTicol011McnoOraRequest(string MCNO, string STAT)
        {
            this.MCNO = MCNO;
            this.STAT = STAT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectTicol011McnoOraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectTicol011McnoOraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceRfidTekni.SelectTicol011McnoOraResponseSelectTicol011McnoOraResult SelectTicol011McnoOraResult;
        
        public SelectTicol011McnoOraResponse()
        {
        }
        
        public SelectTicol011McnoOraResponse(ServiceRfidTekni.SelectTicol011McnoOraResponseSelectTicol011McnoOraResult SelectTicol011McnoOraResult)
        {
            this.SelectTicol011McnoOraResult = SelectTicol011McnoOraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTicol080Ora", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTicol080OraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORNO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PONO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ITEM;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CWAR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QUNE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LOGN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DATE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PROC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CLOT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REFCNTD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REFCNTU;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PDAT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PICK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OORG;
        
        public InsertTicol080OraRequest()
        {
        }
        
        public InsertTicol080OraRequest(string ORNO, string PONO, string ITEM, string CWAR, string QUNE, string LOGN, string DATE, string PROC, string CLOT, string REFCNTD, string REFCNTU, string PDAT, string PICK, string OORG)
        {
            this.ORNO = ORNO;
            this.PONO = PONO;
            this.ITEM = ITEM;
            this.CWAR = CWAR;
            this.QUNE = QUNE;
            this.LOGN = LOGN;
            this.DATE = DATE;
            this.PROC = PROC;
            this.CLOT = CLOT;
            this.REFCNTD = REFCNTD;
            this.REFCNTU = REFCNTU;
            this.PDAT = PDAT;
            this.PICK = PICK;
            this.OORG = OORG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTicol080OraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTicol080OraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool InsertTicol080OraResult;
        
        public InsertTicol080OraResponse()
        {
        }
        
        public InsertTicol080OraResponse(bool InsertTicol080OraResult)
        {
            this.InsertTicol080OraResult = InsertTicol080OraResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SelectWhcol133EvntResponseSelectWhcol133EvntResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectWhcol133Evnt", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectWhcol133EvntRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PROC;
        
        public SelectWhcol133EvntRequest()
        {
        }
        
        public SelectWhcol133EvntRequest(string RFID, string EVNT, string PROC)
        {
            this.RFID = RFID;
            this.EVNT = EVNT;
            this.PROC = PROC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectWhcol133EvntResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectWhcol133EvntResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceRfidTekni.SelectWhcol133EvntResponseSelectWhcol133EvntResult SelectWhcol133EvntResult;
        
        public SelectWhcol133EvntResponse()
        {
        }
        
        public SelectWhcol133EvntResponse(ServiceRfidTekni.SelectWhcol133EvntResponseSelectWhcol133EvntResult SelectWhcol133EvntResult)
        {
            this.SelectWhcol133EvntResult = SelectWhcol133EvntResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWhcol131", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateWhcol131Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PAID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QTYA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string STAT;
        
        public UpdateWhcol131Request()
        {
        }
        
        public UpdateWhcol131Request(string PAID, string QTYA, string STAT)
        {
            this.PAID = PAID;
            this.QTYA = QTYA;
            this.STAT = STAT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWhcol131Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateWhcol131Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateWhcol131Result;
        
        public UpdateWhcol131Response()
        {
        }
        
        public UpdateWhcol131Response(bool UpdateWhcol131Result)
        {
            this.UpdateWhcol131Result = UpdateWhcol131Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitProcRfid", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitProcRfidRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LOGN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PROC;
        
        public InitProcRfidRequest()
        {
        }
        
        public InitProcRfidRequest(string RFID, string EVNT, string LOGN, string PROC)
        {
            this.RFID = RFID;
            this.EVNT = EVNT;
            this.LOGN = LOGN;
            this.PROC = PROC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitProcRfidResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitProcRfidResponse
    {
        
        public InitProcRfidResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitProcRfid022", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitProcRfid022Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LOGN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PROC;
        
        public InitProcRfid022Request()
        {
        }
        
        public InitProcRfid022Request(string RFID, string EVNT, string LOGN, string PROC)
        {
            this.RFID = RFID;
            this.EVNT = EVNT;
            this.LOGN = LOGN;
            this.PROC = PROC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitProcRfid022Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitProcRfid022Response
    {
        
        public InitProcRfid022Response()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitProcRfid025", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitProcRfid025Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LOGN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PROC;
        
        public InitProcRfid025Request()
        {
        }
        
        public InitProcRfid025Request(string RFID, string EVNT, string LOGN, string PROC)
        {
            this.RFID = RFID;
            this.EVNT = EVNT;
            this.LOGN = LOGN;
            this.PROC = PROC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitProcRfid025Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitProcRfid025Response
    {
        
        public InitProcRfid025Response()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitProcRfid025ReprintLabel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitProcRfid025ReprintLabelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        public InitProcRfid025ReprintLabelRequest()
        {
        }
        
        public InitProcRfid025ReprintLabelRequest(string RFID)
        {
            this.RFID = RFID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitProcRfid025ReprintLabelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitProcRfid025ReprintLabelResponse
    {
        
        public InitProcRfid025ReprintLabelResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Updtwhcol133RfidSS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Updtwhcol133RfidSSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PAID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        public Updtwhcol133RfidSSRequest()
        {
        }
        
        public Updtwhcol133RfidSSRequest(string PAID, string RFID)
        {
            this.PAID = PAID;
            this.RFID = RFID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Updtwhcol133RfidSSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Updtwhcol133RfidSSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Updtwhcol133RfidSSResult;
        
        public Updtwhcol133RfidSSResponse()
        {
        }
        
        public Updtwhcol133RfidSSResponse(bool Updtwhcol133RfidSSResult)
        {
            this.Updtwhcol133RfidSSResult = Updtwhcol133RfidSSResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SelectWhcol133OPaidAssingResponseSelectWhcol133OPaidAssingResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectWhcol133OPaidAssing", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectWhcol133OPaidAssingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVNT;
        
        public SelectWhcol133OPaidAssingRequest()
        {
        }
        
        public SelectWhcol133OPaidAssingRequest(string RFID, string EVNT)
        {
            this.RFID = RFID;
            this.EVNT = EVNT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectWhcol133OPaidAssingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectWhcol133OPaidAssingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceRfidTekni.SelectWhcol133OPaidAssingResponseSelectWhcol133OPaidAssingResult SelectWhcol133OPaidAssingResult;
        
        public SelectWhcol133OPaidAssingResponse()
        {
        }
        
        public SelectWhcol133OPaidAssingResponse(ServiceRfidTekni.SelectWhcol133OPaidAssingResponseSelectWhcol133OPaidAssingResult SelectWhcol133OPaidAssingResult)
        {
            this.SelectWhcol133OPaidAssingResult = SelectWhcol133OPaidAssingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert133ss", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert133ssRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PAID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORNO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DATE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LOGN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PROC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REFCNTD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REFCNTU;
        
        public Insert133ssRequest()
        {
        }
        
        public Insert133ssRequest(string PAID, string RFID, string EVNT, string ORNO, string DATE, string LOGN, string PROC, string REFCNTD, string REFCNTU)
        {
            this.PAID = PAID;
            this.RFID = RFID;
            this.EVNT = EVNT;
            this.ORNO = ORNO;
            this.DATE = DATE;
            this.LOGN = LOGN;
            this.PROC = PROC;
            this.REFCNTD = REFCNTD;
            this.REFCNTU = REFCNTU;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert133ssResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert133ssResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Insert133ssResult;
        
        public Insert133ssResponse()
        {
        }
        
        public Insert133ssResponse(bool Insert133ssResult)
        {
            this.Insert133ssResult = Insert133ssResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IService1Channel : ServiceRfidTekni.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceRfidTekni.IService1>, ServiceRfidTekni.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.ConsumirApiResponse> ServiceRfidTekni.IService1.ConsumirApiAsync(ServiceRfidTekni.ConsumirApiRequest request)
        {
            return base.Channel.ConsumirApiAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.ConsumirApiResponse> ConsumirApiAsync(string requestBody)
        {
            ServiceRfidTekni.ConsumirApiRequest inValue = new ServiceRfidTekni.ConsumirApiRequest();
            inValue.requestBody = requestBody;
            return ((ServiceRfidTekni.IService1)(this)).ConsumirApiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.ReseptorResponse> ServiceRfidTekni.IService1.ReseptorAsync(ServiceRfidTekni.ReseptorRequest request)
        {
            return base.Channel.ReseptorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.ReseptorResponse> ReseptorAsync(string Rfid, string Evnt, string Logn)
        {
            ServiceRfidTekni.ReseptorRequest inValue = new ServiceRfidTekni.ReseptorRequest();
            inValue.Rfid = Rfid;
            inValue.Evnt = Evnt;
            inValue.Logn = Logn;
            return ((ServiceRfidTekni.IService1)(this)).ReseptorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.ProWhcol133Response> ServiceRfidTekni.IService1.ProWhcol133Async(ServiceRfidTekni.ProWhcol133Request request)
        {
            return base.Channel.ProWhcol133Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.ProWhcol133Response> ProWhcol133Async(string PAID, string RFID, string EVNT, string ORNO, string DATE, string LOGN, string PROC, string REFCNTD, string REFCNTU)
        {
            ServiceRfidTekni.ProWhcol133Request inValue = new ServiceRfidTekni.ProWhcol133Request();
            inValue.PAID = PAID;
            inValue.RFID = RFID;
            inValue.EVNT = EVNT;
            inValue.ORNO = ORNO;
            inValue.DATE = DATE;
            inValue.LOGN = LOGN;
            inValue.PROC = PROC;
            inValue.REFCNTD = REFCNTD;
            inValue.REFCNTU = REFCNTU;
            return ((ServiceRfidTekni.IService1)(this)).ProWhcol133Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.ProWhcol133OraResponse> ServiceRfidTekni.IService1.ProWhcol133OraAsync(ServiceRfidTekni.ProWhcol133OraRequest request)
        {
            return base.Channel.ProWhcol133OraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.ProWhcol133OraResponse> ProWhcol133OraAsync(string PAID, string RFID, string EVNT, string ORNO, string LOGN, string PROC)
        {
            ServiceRfidTekni.ProWhcol133OraRequest inValue = new ServiceRfidTekni.ProWhcol133OraRequest();
            inValue.PAID = PAID;
            inValue.RFID = RFID;
            inValue.EVNT = EVNT;
            inValue.ORNO = ORNO;
            inValue.LOGN = LOGN;
            inValue.PROC = PROC;
            return ((ServiceRfidTekni.IService1)(this)).ProWhcol133OraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.Update133ssResponse> ServiceRfidTekni.IService1.Update133ssAsync(ServiceRfidTekni.Update133ssRequest request)
        {
            return base.Channel.Update133ssAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.Update133ssResponse> Update133ssAsync(string PAID, string RFID, string EVNT, string ORNO, string DATE, string LOGN, string PROC, string REFCNTD, string REFCNTU)
        {
            ServiceRfidTekni.Update133ssRequest inValue = new ServiceRfidTekni.Update133ssRequest();
            inValue.PAID = PAID;
            inValue.RFID = RFID;
            inValue.EVNT = EVNT;
            inValue.ORNO = ORNO;
            inValue.DATE = DATE;
            inValue.LOGN = LOGN;
            inValue.PROC = PROC;
            inValue.REFCNTD = REFCNTD;
            inValue.REFCNTU = REFCNTU;
            return ((ServiceRfidTekni.IService1)(this)).Update133ssAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133OssResponse> ServiceRfidTekni.IService1.SelectWhcol133OssAsync(ServiceRfidTekni.SelectWhcol133OssRequest request)
        {
            return base.Channel.SelectWhcol133OssAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133OssResponse> SelectWhcol133OssAsync(string RFID, string EVNT)
        {
            ServiceRfidTekni.SelectWhcol133OssRequest inValue = new ServiceRfidTekni.SelectWhcol133OssRequest();
            inValue.RFID = RFID;
            inValue.EVNT = EVNT;
            return ((ServiceRfidTekni.IService1)(this)).SelectWhcol133OssAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133ORfidssResponse> ServiceRfidTekni.IService1.SelectWhcol133ORfidssAsync(ServiceRfidTekni.SelectWhcol133ORfidssRequest request)
        {
            return base.Channel.SelectWhcol133ORfidssAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133ORfidssResponse> SelectWhcol133ORfidssAsync(string RFID, string EVNT)
        {
            ServiceRfidTekni.SelectWhcol133ORfidssRequest inValue = new ServiceRfidTekni.SelectWhcol133ORfidssRequest();
            inValue.RFID = RFID;
            inValue.EVNT = EVNT;
            return ((ServiceRfidTekni.IService1)(this)).SelectWhcol133ORfidssAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol131OraResponse> ServiceRfidTekni.IService1.SelectWhcol131OraAsync(ServiceRfidTekni.SelectWhcol131OraRequest request)
        {
            return base.Channel.SelectWhcol131OraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol131OraResponse> SelectWhcol131OraAsync(string PAID)
        {
            ServiceRfidTekni.SelectWhcol131OraRequest inValue = new ServiceRfidTekni.SelectWhcol131OraRequest();
            inValue.PAID = PAID;
            return ((ServiceRfidTekni.IService1)(this)).SelectWhcol131OraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectTicol011McnoOraResponse> ServiceRfidTekni.IService1.SelectTicol011McnoOraAsync(ServiceRfidTekni.SelectTicol011McnoOraRequest request)
        {
            return base.Channel.SelectTicol011McnoOraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.SelectTicol011McnoOraResponse> SelectTicol011McnoOraAsync(string MCNO, string STAT)
        {
            ServiceRfidTekni.SelectTicol011McnoOraRequest inValue = new ServiceRfidTekni.SelectTicol011McnoOraRequest();
            inValue.MCNO = MCNO;
            inValue.STAT = STAT;
            return ((ServiceRfidTekni.IService1)(this)).SelectTicol011McnoOraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.InsertTicol080OraResponse> ServiceRfidTekni.IService1.InsertTicol080OraAsync(ServiceRfidTekni.InsertTicol080OraRequest request)
        {
            return base.Channel.InsertTicol080OraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.InsertTicol080OraResponse> InsertTicol080OraAsync(string ORNO, string PONO, string ITEM, string CWAR, string QUNE, string LOGN, string DATE, string PROC, string CLOT, string REFCNTD, string REFCNTU, string PDAT, string PICK, string OORG)
        {
            ServiceRfidTekni.InsertTicol080OraRequest inValue = new ServiceRfidTekni.InsertTicol080OraRequest();
            inValue.ORNO = ORNO;
            inValue.PONO = PONO;
            inValue.ITEM = ITEM;
            inValue.CWAR = CWAR;
            inValue.QUNE = QUNE;
            inValue.LOGN = LOGN;
            inValue.DATE = DATE;
            inValue.PROC = PROC;
            inValue.CLOT = CLOT;
            inValue.REFCNTD = REFCNTD;
            inValue.REFCNTU = REFCNTU;
            inValue.PDAT = PDAT;
            inValue.PICK = PICK;
            inValue.OORG = OORG;
            return ((ServiceRfidTekni.IService1)(this)).InsertTicol080OraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133EvntResponse> ServiceRfidTekni.IService1.SelectWhcol133EvntAsync(ServiceRfidTekni.SelectWhcol133EvntRequest request)
        {
            return base.Channel.SelectWhcol133EvntAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133EvntResponse> SelectWhcol133EvntAsync(string RFID, string EVNT, string PROC)
        {
            ServiceRfidTekni.SelectWhcol133EvntRequest inValue = new ServiceRfidTekni.SelectWhcol133EvntRequest();
            inValue.RFID = RFID;
            inValue.EVNT = EVNT;
            inValue.PROC = PROC;
            return ((ServiceRfidTekni.IService1)(this)).SelectWhcol133EvntAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.UpdateWhcol131Response> ServiceRfidTekni.IService1.UpdateWhcol131Async(ServiceRfidTekni.UpdateWhcol131Request request)
        {
            return base.Channel.UpdateWhcol131Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.UpdateWhcol131Response> UpdateWhcol131Async(string PAID, string QTYA, string STAT)
        {
            ServiceRfidTekni.UpdateWhcol131Request inValue = new ServiceRfidTekni.UpdateWhcol131Request();
            inValue.PAID = PAID;
            inValue.QTYA = QTYA;
            inValue.STAT = STAT;
            return ((ServiceRfidTekni.IService1)(this)).UpdateWhcol131Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfidResponse> ServiceRfidTekni.IService1.InitProcRfidAsync(ServiceRfidTekni.InitProcRfidRequest request)
        {
            return base.Channel.InitProcRfidAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfidResponse> InitProcRfidAsync(string RFID, string EVNT, string LOGN, string PROC)
        {
            ServiceRfidTekni.InitProcRfidRequest inValue = new ServiceRfidTekni.InitProcRfidRequest();
            inValue.RFID = RFID;
            inValue.EVNT = EVNT;
            inValue.LOGN = LOGN;
            inValue.PROC = PROC;
            return ((ServiceRfidTekni.IService1)(this)).InitProcRfidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfid022Response> ServiceRfidTekni.IService1.InitProcRfid022Async(ServiceRfidTekni.InitProcRfid022Request request)
        {
            return base.Channel.InitProcRfid022Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfid022Response> InitProcRfid022Async(string RFID, string EVNT, string LOGN, string PROC)
        {
            ServiceRfidTekni.InitProcRfid022Request inValue = new ServiceRfidTekni.InitProcRfid022Request();
            inValue.RFID = RFID;
            inValue.EVNT = EVNT;
            inValue.LOGN = LOGN;
            inValue.PROC = PROC;
            return ((ServiceRfidTekni.IService1)(this)).InitProcRfid022Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfid025Response> ServiceRfidTekni.IService1.InitProcRfid025Async(ServiceRfidTekni.InitProcRfid025Request request)
        {
            return base.Channel.InitProcRfid025Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfid025Response> InitProcRfid025Async(string RFID, string EVNT, string LOGN, string PROC)
        {
            ServiceRfidTekni.InitProcRfid025Request inValue = new ServiceRfidTekni.InitProcRfid025Request();
            inValue.RFID = RFID;
            inValue.EVNT = EVNT;
            inValue.LOGN = LOGN;
            inValue.PROC = PROC;
            return ((ServiceRfidTekni.IService1)(this)).InitProcRfid025Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfid025ReprintLabelResponse> ServiceRfidTekni.IService1.InitProcRfid025ReprintLabelAsync(ServiceRfidTekni.InitProcRfid025ReprintLabelRequest request)
        {
            return base.Channel.InitProcRfid025ReprintLabelAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.InitProcRfid025ReprintLabelResponse> InitProcRfid025ReprintLabelAsync(string RFID)
        {
            ServiceRfidTekni.InitProcRfid025ReprintLabelRequest inValue = new ServiceRfidTekni.InitProcRfid025ReprintLabelRequest();
            inValue.RFID = RFID;
            return ((ServiceRfidTekni.IService1)(this)).InitProcRfid025ReprintLabelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.Updtwhcol133RfidSSResponse> ServiceRfidTekni.IService1.Updtwhcol133RfidSSAsync(ServiceRfidTekni.Updtwhcol133RfidSSRequest request)
        {
            return base.Channel.Updtwhcol133RfidSSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.Updtwhcol133RfidSSResponse> Updtwhcol133RfidSSAsync(string PAID, string RFID)
        {
            ServiceRfidTekni.Updtwhcol133RfidSSRequest inValue = new ServiceRfidTekni.Updtwhcol133RfidSSRequest();
            inValue.PAID = PAID;
            inValue.RFID = RFID;
            return ((ServiceRfidTekni.IService1)(this)).Updtwhcol133RfidSSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133OPaidAssingResponse> ServiceRfidTekni.IService1.SelectWhcol133OPaidAssingAsync(ServiceRfidTekni.SelectWhcol133OPaidAssingRequest request)
        {
            return base.Channel.SelectWhcol133OPaidAssingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.SelectWhcol133OPaidAssingResponse> SelectWhcol133OPaidAssingAsync(string RFID, string EVNT)
        {
            ServiceRfidTekni.SelectWhcol133OPaidAssingRequest inValue = new ServiceRfidTekni.SelectWhcol133OPaidAssingRequest();
            inValue.RFID = RFID;
            inValue.EVNT = EVNT;
            return ((ServiceRfidTekni.IService1)(this)).SelectWhcol133OPaidAssingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceRfidTekni.Insert133ssResponse> ServiceRfidTekni.IService1.Insert133ssAsync(ServiceRfidTekni.Insert133ssRequest request)
        {
            return base.Channel.Insert133ssAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceRfidTekni.Insert133ssResponse> Insert133ssAsync(string PAID, string RFID, string EVNT, string ORNO, string DATE, string LOGN, string PROC, string REFCNTD, string REFCNTU)
        {
            ServiceRfidTekni.Insert133ssRequest inValue = new ServiceRfidTekni.Insert133ssRequest();
            inValue.PAID = PAID;
            inValue.RFID = RFID;
            inValue.EVNT = EVNT;
            inValue.ORNO = ORNO;
            inValue.DATE = DATE;
            inValue.LOGN = LOGN;
            inValue.PROC = PROC;
            inValue.REFCNTD = REFCNTD;
            inValue.REFCNTU = REFCNTU;
            return ((ServiceRfidTekni.IService1)(this)).Insert133ssAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("https://gpbfpr.tekni-plex.com/RfidService1/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IService1,
        }
    }
}
